[MainWindow]
AdvToolbar=
FSCtoolbar=
InputToolbar="43-1;33;44-1;"
MainToolbar1=
MainToolbar2=
QtStyle=kvantum-dark
ShowRemainingTime=false
ToolbarPos=false
adv-controls=0
pl-dock-status=false
playlist-visible=false
status-bar-visible=false
