# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[status]
separator_open  = ""
separator_close = ""

[icon]
files = [
	{ name = ".dockerignore", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = ".mailmap", text = "", fg_dark = "#41535b", fg_light = "#41535b" },
	{ name = ".SRCINFO", text = "", fg_dark = "#0f94d2", fg_light = "#0b6f9e" },
	{ name = "bspwmrc", text = "", fg_dark = "#2f2f2f", fg_light = "#2f2f2f" },
	{ name = "checkhealth", text = "", fg_dark = "#75b4fb", fg_light = "#3a5a7e" },
	{ name = "compose.yaml", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = "compose.yml", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = "containerfile", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = "docker-compose.yaml", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = "docker-compose.yml", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = "dockerfile", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = "fp-info-cache", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "fp-lib-table", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "FreeCAD.conf", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "kdenlive-layoutsrc", text = "", fg_dark = "#83b8f2", fg_light = "#425c79" },
	{ name = "kdenliverc", text = "", fg_dark = "#83b8f2", fg_light = "#425c79" },
	{ name = "kritadisplayrc", text = "", fg_dark = "#f245fb", fg_light = "#a12ea7" },
	{ name = "kritarc", text = "", fg_dark = "#f245fb", fg_light = "#a12ea7" },
	{ name = "lxqt.conf", text = "", fg_dark = "#0192d3", fg_light = "#016e9e" },
	{ name = "PrusaSlicer.ini", text = "", fg_dark = "#ec6b23", fg_light = "#9d4717" },
	{ name = "PrusaSlicerGcodeViewer.ini", text = "", fg_dark = "#ec6b23", fg_light = "#9d4717" },
	{ name = "R", text = "", fg_dark = "#2266ba", fg_light = "#1a4c8c" },
	{ name = "r", text = "", fg_dark = "#2266ba", fg_light = "#1a4c8c" },
	{ name = "sxhkdrc", text = "", fg_dark = "#2f2f2f", fg_light = "#2f2f2f" },
	{ name = "sym-lib-table", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "tailwind.config.js", text = "", fg_dark = "#20c2e3", fg_light = "#158197" },
	{ name = "tailwind.config.mjs", text = "", fg_dark = "#20c2e3", fg_light = "#158197" },
	{ name = "tailwind.config.ts", text = "", fg_dark = "#20c2e3", fg_light = "#158197" },
	{ name = "vlcrc", text = "", fg_dark = "#ee7a00", fg_light = "#9f5100" },
	{ name = "webpack", text = "", fg_dark = "#519aba", fg_light = "#36677c" },
	{ name = "weston.ini", text = "", fg_dark = "#ffbb01", fg_light = "#805e00" },
	{ name = "xmobarrc", text = "", fg_dark = "#fd4d5d", fg_light = "#a9333e" },
	{ name = "xmobarrc.hs", text = "", fg_dark = "#fd4d5d", fg_light = "#a9333e" },
	{ name = "xmonad.hs", text = "", fg_dark = "#fd4d5d", fg_light = "#a9333e" },
]
exts = [
	{ name = "3mf", text = "", fg_dark = "#888888", fg_light = "#5b5b5b" },
	{ name = "asc", text = "", fg_dark = "#576d7f", fg_light = "#41525f" },
	{ name = "ass", text = "", fg_dark = "#ffb713", fg_light = "#805c0a" },
	{ name = "bak", text = "", fg_dark = "#6d8086", fg_light = "#526064" },
	{ name = "bib", text = "", fg_dark = "#cbcb41", fg_light = "#666620" },
	{ name = "blade.php", text = "", fg_dark = "#f05340", fg_light = "#a0372b" },
	{ name = "blend", text = "", fg_dark = "#ea7600", fg_light = "#9c4f00" },
	{ name = "blp", text = "", fg_dark = "#5796e2", fg_light = "#3a6497" },
	{ name = "brep", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "cs", text = "", fg_dark = "#596706", fg_light = "#434d04" },
	{ name = "cshtml", text = "", fg_dark = "#512bd4", fg_light = "#512bd4" },
	{ name = "csproj", text = "", fg_dark = "#512bd4", fg_light = "#512bd4" },
	{ name = "cue", text = "", fg_dark = "#ed95ae", fg_light = "#764a57" },
	{ name = "dconf", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "doc", text = "", fg_dark = "#185abd", fg_light = "#185abd" },
	{ name = "Dockerfile", text = "", fg_dark = "#458ee6", fg_light = "#2e5f99" },
	{ name = "docx", text = "", fg_dark = "#185abd", fg_light = "#185abd" },
	{ name = "dot", text = "", fg_dark = "#30638e", fg_light = "#244a6a" },
	{ name = "dwg", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "dxf", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "f3d", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "f90", text = "", fg_dark = "#734f96", fg_light = "#563b70" },
	{ name = "fbx", text = "", fg_dark = "#888888", fg_light = "#5b5b5b" },
	{ name = "fcbak", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fcmacro", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fcmat", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fcparam", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fcscript", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fcstd", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fcstd1", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fctb", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "fctl", text = "", fg_dark = "#cb0d0d", fg_light = "#cb0d0d" },
	{ name = "gcode", text = "", fg_dark = "#1471ad", fg_light = "#0f5582" },
	{ name = "gv", text = "", fg_dark = "#30638e", fg_light = "#244a6a" },
	{ name = "huff", text = "", fg_dark = "#4242c7", fg_light = "#4242c7" },
	{ name = "ifc", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "ige", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "iges", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "igs", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "ino", text = "", fg_dark = "#56b6c2", fg_light = "#397981" },
	{ name = "kbx", text = "", fg_dark = "#737672", fg_light = "#565856" },
	{ name = "kdenlive", text = "", fg_dark = "#83b8f2", fg_light = "#425c79" },
	{ name = "kdenlivetitle", text = "", fg_dark = "#83b8f2", fg_light = "#425c79" },
	{ name = "kicad_dru", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kicad_mod", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kicad_pcb", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kicad_prl", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kicad_pro", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kicad_sch", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kicad_sym", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kicad_wks", text = "", fg_dark = "#ffffff", fg_light = "#333333" },
	{ name = "kpp", text = "", fg_dark = "#f245fb", fg_light = "#a12ea7" },
	{ name = "kra", text = "", fg_dark = "#f245fb", fg_light = "#a12ea7" },
	{ name = "krz", text = "", fg_dark = "#f245fb", fg_light = "#a12ea7" },
	{ name = "log", text = "", fg_dark = "#dddddd", fg_light = "#4a4a4a" },
	{ name = "lrc", text = "", fg_dark = "#ffb713", fg_light = "#805c0a" },
	{ name = "m3u", text = "", fg_dark = "#ed95ae", fg_light = "#764a57" },
	{ name = "m3u8", text = "", fg_dark = "#ed95ae", fg_light = "#764a57" },
	{ name = "material", text = "", fg_dark = "#b83998", fg_light = "#8a2b72" },
	{ name = "md5", text = "", fg_dark = "#8c86af", fg_light = "#5d5975" },
	{ name = "mint", text = "", fg_dark = "#87c095", fg_light = "#44604a" },
	{ name = "obj", text = "", fg_dark = "#888888", fg_light = "#5b5b5b" },
	{ name = "pls", text = "", fg_dark = "#ed95ae", fg_light = "#764a57" },
	{ name = "ply", text = "", fg_dark = "#888888", fg_light = "#5b5b5b" },
	{ name = "ppt", text = "", fg_dark = "#cb4a32", fg_light = "#983826" },
	{ name = "ps1", text = "", fg_dark = "#4273ca", fg_light = "#325698" },
	{ name = "psd1", text = "", fg_dark = "#6975c4", fg_light = "#4f5893" },
	{ name = "psm1", text = "", fg_dark = "#6975c4", fg_light = "#4f5893" },
	{ name = "pub", text = "", fg_dark = "#e3c58e", fg_light = "#4c422f" },
	{ name = "r", text = "", fg_dark = "#2266ba", fg_light = "#1a4c8c" },
	{ name = "razor", text = "", fg_dark = "#512bd4", fg_light = "#512bd4" },
	{ name = "rproj", text = "", fg_dark = "#358a5b", fg_light = "#286844" },
	{ name = "scad", text = "", fg_dark = "#f9d72c", fg_light = "#53480f" },
	{ name = "scm", text = "", fg_dark = "#eeeeee", fg_light = "#303030" },
	{ name = "sha1", text = "", fg_dark = "#8c86af", fg_light = "#5d5975" },
	{ name = "sha224", text = "", fg_dark = "#8c86af", fg_light = "#5d5975" },
	{ name = "sha256", text = "", fg_dark = "#8c86af", fg_light = "#5d5975" },
	{ name = "sha384", text = "", fg_dark = "#8c86af", fg_light = "#5d5975" },
	{ name = "sha512", text = "", fg_dark = "#8c86af", fg_light = "#5d5975" },
	{ name = "skp", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "sldasm", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "sldprt", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "slvs", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "srt", text = "", fg_dark = "#ffb713", fg_light = "#805c0a" },
	{ name = "ssa", text = "", fg_dark = "#ffb713", fg_light = "#805c0a" },
	{ name = "ste", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "step", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "stl", text = "", fg_dark = "#888888", fg_light = "#5b5b5b" },
	{ name = "stp", text = "", fg_dark = "#839463", fg_light = "#576342" },
	{ name = "sub", text = "", fg_dark = "#ffb713", fg_light = "#805c0a" },
	{ name = "sv", text = "", fg_dark = "#019833", fg_light = "#017226" },
	{ name = "svg", text = "", fg_dark = "#ffb13b", fg_light = "#80581e" },
	{ name = "svh", text = "", fg_dark = "#019833", fg_light = "#017226" },
	{ name = "tbc", text = "", fg_dark = "#1e5cb3", fg_light = "#1e5cb3" },
	{ name = "tcl", text = "", fg_dark = "#1e5cb3", fg_light = "#1e5cb3" },
	{ name = "txt", text = "", fg_dark = "#89e051", fg_light = "#447028" },
	{ name = "v", text = "", fg_dark = "#019833", fg_light = "#017226" },
	{ name = "vh", text = "", fg_dark = "#019833", fg_light = "#017226" },
	{ name = "vhd", text = "", fg_dark = "#019833", fg_light = "#017226" },
	{ name = "vhdl", text = "", fg_dark = "#019833", fg_light = "#017226" },
	{ name = "webpack", text = "", fg_dark = "#519aba", fg_light = "#36677c" },
	{ name = "wrl", text = "", fg_dark = "#888888", fg_light = "#5b5b5b" },
	{ name = "wrz", text = "", fg_dark = "#888888", fg_light = "#5b5b5b" },
	{ name = "xaml", text = "", fg_dark = "#512bd4", fg_light = "#512bd4" },
	{ name = "xls", text = "", fg_dark = "#207245", fg_light = "#207245" },
	{ name = "xlsx", text = "", fg_dark = "#207245", fg_light = "#207245" },
	{ name = "xml", text = "", fg_dark = "#e37933", fg_light = "#975122" },
]
conds = [
	{ if = "dir", text = "" },
	{ if = "exec", text = "" },
	{ if = "!dir", text = "" },
]
