# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden    = true
title_format   = "{cwd}"
linemode = "size_and_mtime"

[opener]
edit = [
	{ run = 'neovide "$@"', orphan = true, desc = "neovide", for = "unix" },
]
term = [
	{ run = 'alacritty --working-directory "$@"', orphan = true, desc = "alacritty", for = "unix" },
]

[open]
prepend_rules = [
	{ mime = "inode/directory", use = "term" },
]
